package com.tao.www.config.config;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;
import com.tao.www.model.Authority;
import com.tao.www.model.Department;
import com.tao.www.model.DepartmentCollection;
import com.tao.www.model.DepartmentOption;
import com.tao.www.model.DepartmentQuestion;
import com.tao.www.model.DepartmentResult;
import com.tao.www.model.DepartmentResultDetail;
import com.tao.www.model.DepartmentType;
import com.tao.www.model.EdCollection;
import com.tao.www.model.EeCollection;
import com.tao.www.model.Employee;
import com.tao.www.model.EmployeeOption;
import com.tao.www.model.EmployeeQuestionBasic;
import com.tao.www.model.EmployeeQuestionStandard;
import com.tao.www.model.EmployeeResult;
import com.tao.www.model.EmployeeResultDetail;
import com.tao.www.model.EmployeeToDepartment;
import com.tao.www.model.EmployeeToEmployee;
import com.tao.www.model.EmployeeToRole;
import com.tao.www.model.Grade;
import com.tao.www.model.Now;
import com.tao.www.model.Progress;
import com.tao.www.model.Role;
import com.tao.www.model.RoleToAuthority;
import com.tao.www.model.SatisfyQuestion;
import com.tao.www.model.SatisfyResult;
import com.tao.www.model.SatisfyResultDetail;
import com.tao.www.model.Statistic;
import com.tao.www.model.TotalScale;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		//映射t_department_type表到DepartmentType模型
		arp.addMapping("t_department_type","dtid",DepartmentType.class);
		//映射t_department表到Department模型
		arp.addMapping("t_department","did",Department.class);
		//映射t_employee表到Employee模型
		arp.addMapping("t_employee","eid",Employee.class);
		//映射t_role表到Role模型
		arp.addMapping("t_role","rid",Role.class);
		//映射t_employee_department表到EmployeeToDepartment模型
		arp.addMapping("t_employee_department","eid,did",EmployeeToDepartment.class);
		//映射t_authority表到Authority模型
		arp.addMapping("t_authority","aid",Authority.class);
		//映射t_role_authority表到RoleToAuthority模型
		arp.addMapping("t_role_authority","rid,aid",RoleToAuthority.class);
		//映射t_employee_role表到EmployeeToRole模型
		arp.addMapping("t_employee_role","eid,rid",EmployeeToRole.class);
		//映射t_department_question表到DepartmentQuestion模型
		arp.addMapping("t_department_question","dqid",DepartmentQuestion.class);
		//映射t_department_option表到DepartmentOption模型
		arp.addMapping("t_department_option","doid",DepartmentOption.class);
		//映射t_statistic表到Statistic模型
		arp.addMapping("t_statistic","sid",Statistic.class);
		//映射t_grade表到Grade模型
		arp.addMapping("t_grade","gid",Grade.class);
		//映射t_satisfy_question表到SatisfyQuestion模型
		arp.addMapping("t_satisfy_question","sqid",SatisfyQuestion.class);
		//映射t_employee_question_basic表到EmployeeQuestionBasic模型
		arp.addMapping("t_employee_question_basic","eqbid",EmployeeQuestionBasic.class);
		//映射t_employee_question_standard表到EmployeeQuestionBasic模型
		arp.addMapping("t_employee_question_standard","eqsid",EmployeeQuestionStandard.class);
		//映射t_employee_option表到EmployeeOption模型
		arp.addMapping("t_employee_option","eoid",EmployeeOption.class);
		//映射t_employee_employee表到EmployeeTOEmployee模型
		arp.addMapping("t_employee_employee","eid,eeid",EmployeeToEmployee.class);
		//映射t_total_scale表到TotalScale模型
		arp.addMapping("t_total_scale","tsid",TotalScale.class);
		//映射t_total_scale表到TotalScale模型
		arp.addMapping("t_satisfy_result","srid",SatisfyResult.class);
		//映射t_satisfy_result_detail表到SatisfyResultDetail模型
		arp.addMapping("t_satisfy_result_detail","srdid",SatisfyResultDetail.class);
		//映射t_department_result表到DepartmentResult模型
		arp.addMapping("t_department_result","drid",DepartmentResult.class);
		//映射t_department_result_detail表到DepartmentResultDetail模型
		arp.addMapping("t_department_result_detail","drdid",DepartmentResultDetail.class);
		//映射t_employee_result表到EmployeeResult模型
		arp.addMapping("t_employee_result","erid",EmployeeResult.class);
		//映射t_employee_result_detail表到EmployeeResultDetail模型
		arp.addMapping("t_employee_result_detail","erdid",EmployeeResultDetail.class);
		//映射t_progress表到Progress模型
		arp.addMapping("t_progress","pid",Progress.class);
		//映射t_department_collection表到DepartmentCollection模型
		arp.addMapping("t_department_collection","dcid",DepartmentCollection.class);
		//映射t_ed_collection表到EdCollection模型
		arp.addMapping("t_ed_collection","edcid",EdCollection.class);
		//映射t_ee_collection表到EeCollection模型
		arp.addMapping("t_ee_collection","eecid",EeCollection.class);
		//映射t_now表到EeCollection模型
		arp.addMapping("t_now","id",Now.class);
	}
}

